// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdrdhpwhuisuhsjvwswt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkcmRocHdodWlzdWhzanZ3c3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MDc5NTYsImV4cCI6MjA4NDQ4Mzk1Nn0.cQo1su7EFHCbNlTwtCwYOl7eOIYmxrNKB3jVypblBrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});